import Head from 'next/head';
import Image from 'next/image';
import Hero from '../components/Hero/hero';
import Main from '../components/Main/main';

import TopBar from '../components/topbar';

export default function Home() {
  return (
    <div className="">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <TopBar />
      <Hero />
      <Main />
    </div>
  );
}
